# system-wide requirements
ubuntu: # for ubuntu hosts
  apt:
    packages:
      - build-essential
      - mdm # for nproc

generic: # for any host
  programs:
    in_path:
      - make
      - c2rust