#!/usr/bin/env bash
# this file was autogenerated by templates.py
set -e; set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0" )" && pwd)"

RUST_BACKTRACE=1 c2rust transpile \
    --output-dir "$SCRIPT_DIR/repo" --main nginx \
     ${EXTRA_TFLAGS:---overwrite-existing} \
    compile_commands.json \
    --  ${EXTRA_CFLAGS:--w} \
     2>&1 | tee `basename "$0"`.log

if [[ -f "$SCRIPT_DIR/build.rs" ]]; then
    cp "$SCRIPT_DIR/build.rs" "$SCRIPT_DIR/repo"
fi